# Generated by Django 4.2.4 on 2023-08-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CDR',
            new_name='ChargeDataRecord',
        ),
    ]
